### ISSUE TITLE
Possibly incorrect L_max in the objective function

### ISSUE THREAD

**Issue by joschout** [jirifilip/pyIDS#1]
L_max is incorrectly calculated in the part of the objective function minimizing the number of literals in the current ruleset. 

This part of the objective function uses as an upper bound L_max * len_all_rules, with:

- len_all_rules: the total number of all possible rules
-  L_max: length of the longest rule over all possible rules, in number of predicates.

Currently,  L_max is calculated over the current ruleset, which is a subset of the initial set of rules. It should be calculated over all rules.

https://github.com/jirifilip/pyIDS/blob/adf546d9706b70494c72c0f02ebaa46979ac9f06/pyids/data_structures/ids_objective_function.py#L43

**Comment by jirifilip** [comment]
Thank you, I will have a look as soon as possible.

**Comment by jirifilip** [comment]
Thank you for catching that, It's now corrected
