### ISSUE TITLE
Bug: removing an integer from a set of IDSRules

### ISSUE THREAD

**Issue by joschout** [jirifilip/pyIDS#3]
https://github.com/jirifilip/pyIDS/blob/7c5ef43a9d2eff2cc724034a4b288cf8f09411f4/pyids/data_structures/ids_optimizer.py#L133

Inside the optimize_delta() method of the SLSOptiimizer, there is an iteration over the rules in the current solution set. This iteration uses an enumeration, giving back both an index in the array or omega_estimates and the corresponding rule. When the omega_estimate for the current rule is below the threshold value, the current rule must be removed from the current solution set.

`soln_set.ruleset.remove(rule_idx) `should be changed to `soln_set.ruleset.remove(rule)`.

Currently, this can result in a KeyError

**Comment by jirifilip** [comment]
Thank you, the issue is now corrected
