### ISSUE TITLE
missing pyarc file

### ISSUE THREAD

**Issue by ruilialice** [jirifilip/pyIDS#4]
Dear Jiri,
It seems that in pyIDS, pyarc file is missing. In the examples you posted, it has "from pyarc.qcba.data_structures import QuantitativeDataFrame", but it seems that there is no "pyarc" file.

**Comment by kliegr** [comment]
You may need to install pyARC package either via pypi, or from GitHub (https://github.com/jirifilip/pyARC)

**Comment by jirifilip** [comment]
Hello, sorry, it is as @kliegr said. For future reference, I added an "Installation" section to the README file, explaining the dependencies of pyIDS.
